INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (1, 'Autopilot', NOW()) ON DUPLICATE KEY UPDATE name='Autopilot', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (2, 'Cockpit speakers', NOW()) ON DUPLICATE KEY UPDATE name='Cockpit speakers', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (3, 'DVD player', NOW()) ON DUPLICATE KEY UPDATE name='DVD player', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (4, 'Dinghy', NOW()) ON DUPLICATE KEY UPDATE name='Dinghy', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (5, 'Chart plotter', NOW()) ON DUPLICATE KEY UPDATE name='Chart plotter', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (6, 'Electric winches', NOW()) ON DUPLICATE KEY UPDATE name='Electric winches', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (7, 'Bimini', NOW()) ON DUPLICATE KEY UPDATE name='Bimini', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (8, 'Flybridge', NOW()) ON DUPLICATE KEY UPDATE name='Flybridge', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (9, 'Bow thruster', NOW()) ON DUPLICATE KEY UPDATE name='Bow thruster', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (10, 'Radar', NOW()) ON DUPLICATE KEY UPDATE name='Radar', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (11, 'Heating', NOW()) ON DUPLICATE KEY UPDATE name='Heating', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (12, 'Generator', NOW()) ON DUPLICATE KEY UPDATE name='Generator', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (13, 'Lazy jack', NOW()) ON DUPLICATE KEY UPDATE name='Lazy jack', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (14, 'Radio-CD player', NOW()) ON DUPLICATE KEY UPDATE name='Radio-CD player', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (16, 'Sprayhood', NOW()) ON DUPLICATE KEY UPDATE name='Sprayhood', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (17, 'Chart plotter in cockpit', NOW()) ON DUPLICATE KEY UPDATE name='Chart plotter in cockpit', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (18, 'Outboard engine', NOW()) ON DUPLICATE KEY UPDATE name='Outboard engine', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (19, 'Teak deck', NOW()) ON DUPLICATE KEY UPDATE name='Teak deck', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (21, 'Wi-Fi & Internet', NOW()) ON DUPLICATE KEY UPDATE name='Wi-Fi & Internet', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (22, 'Game console', NOW()) ON DUPLICATE KEY UPDATE name='Game console', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (23, 'Stand up paddle', NOW()) ON DUPLICATE KEY UPDATE name='Stand up paddle', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (25, 'Coffee maker', NOW()) ON DUPLICATE KEY UPDATE name='Coffee maker', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (26, 'Diving equipment', NOW()) ON DUPLICATE KEY UPDATE name='Diving equipment', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (27, 'Electric toilet', NOW()) ON DUPLICATE KEY UPDATE name='Electric toilet', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (29, 'Air condition', NOW()) ON DUPLICATE KEY UPDATE name='Air condition', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (30, 'Holding tank', NOW()) ON DUPLICATE KEY UPDATE name='Holding tank', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (31, 'Hydraulic gangway', NOW()) ON DUPLICATE KEY UPDATE name='Hydraulic gangway', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (32, 'Spinnaker', NOW()) ON DUPLICATE KEY UPDATE name='Spinnaker', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (33, 'Inverter', NOW()) ON DUPLICATE KEY UPDATE name='Inverter', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (34, 'Ice maker', NOW()) ON DUPLICATE KEY UPDATE name='Ice maker', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (35, 'Lazy bag', NOW()) ON DUPLICATE KEY UPDATE name='Lazy bag', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (36, 'Railing net', NOW()) ON DUPLICATE KEY UPDATE name='Railing net', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (37, 'Refrigerator', NOW()) ON DUPLICATE KEY UPDATE name='Refrigerator', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (40, 'Snorkeling equipment', NOW()) ON DUPLICATE KEY UPDATE name='Snorkeling equipment', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (41, 'Gennaker', NOW()) ON DUPLICATE KEY UPDATE name='Gennaker', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (42, 'TV', NOW()) ON DUPLICATE KEY UPDATE name='TV', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (43, 'Racing sails', NOW()) ON DUPLICATE KEY UPDATE name='Racing sails', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (44, 'Water maker', NOW()) ON DUPLICATE KEY UPDATE name='Water maker', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (45, 'Cockpit cushions', NOW()) ON DUPLICATE KEY UPDATE name='Cockpit cushions', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (46, 'Solar Panels', NOW()) ON DUPLICATE KEY UPDATE name='Solar Panels', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (47, 'Teak Cockpit', NOW()) ON DUPLICATE KEY UPDATE name='Teak Cockpit', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (48, 'Barbecue grill in cockpit', NOW()) ON DUPLICATE KEY UPDATE name='Barbecue grill in cockpit', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (49, 'Outside Steering Position', NOW()) ON DUPLICATE KEY UPDATE name='Outside Steering Position', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (50, 'Swimming platform', NOW()) ON DUPLICATE KEY UPDATE name='Swimming platform', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (51, 'Swimming pool', NOW()) ON DUPLICATE KEY UPDATE name='Swimming pool', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (52, 'Dishwasher', NOW()) ON DUPLICATE KEY UPDATE name='Dishwasher', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (53, 'Washer/Dryer', NOW()) ON DUPLICATE KEY UPDATE name='Washer/Dryer', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (54, 'Underwater lights', NOW()) ON DUPLICATE KEY UPDATE name='Underwater lights', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (55, 'Tenderlift platform', NOW()) ON DUPLICATE KEY UPDATE name='Tenderlift platform', last_synced=NOW();
INSERT INTO wp_yolo_equipment_catalog (id, name, last_synced) VALUES (56, 'Tender garage', NOW()) ON DUPLICATE KEY UPDATE name='Tender garage', last_synced=NOW();
